name: CI for todolist

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Cache Poetry
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: poetry install

    - name: Check PEP 8 compliance
      run: poetry run flake8

    - name: Run specified test with coverage
      run: |
        poetry run coverage run -m unittest tests/test_tache.py

    - name: Generate coverage report
      run: poetry run coverage report
