name: Python CI/CD with Poetry for todolist

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip install autopep8
      - run: autopep8 --recursive --in-place .
      - run: git config --global user.name 'GitHub Actions'
      - run: git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - run: git add -A
      - run: git commit -m "Format code with autopep8" || echo "No changes to commit"
      - run: git push

  unittest:
    needs: autopep8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry install
      - run: poetry run python -m unittest tests/test_tache.py

  coverage:
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry install
      - run: poetry run coverage run -m unittest tests/test_tache.py
      - run: poetry run coverage report -m

  build:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry install
      - run: poetry build