name: Python CI/CD with Poetry for todolist

on:
  push:
    branches:
      - main

jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.11'
      - run: pip install autopep8
      - run: autopep8 --recursive --in-place .
      - run: git config --global user.name 'GitHub Actions'
      - run: git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - run: git add -A
      - run: git commit -m "Format code with autopep8" || echo "No changes to commit"
      - run: git push

  unittest:
    needs: autopep8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.11'
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry install
      - run: poetry run python -m unittest tests/test_tache.py
      - run: poetry run python -m unittest tests/test_todolist.py

  coverage:
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.11'
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry install
      - run: poetry run coverage run -m unittest tests/test_tache.py
      - run: poetry run coverage run -a -m unittest tests/test_todolist.py
      - run: poetry run coverage report -m > coverage.txt
      - run: |
          COVERAGE=$(poetry run coverage report -m | grep 'TOTAL' | awk '{print $6}' | sed 's/%//')
          echo "Coverage: $COVERAGE%"
          if [[ "$COVERAGE" -lt 90 ]]; then
            echo "Test coverage is below 90%."
            exit 1
          fi
      # Add access to the report
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.txt

  build:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.11'
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry install
      - run: poetry build
